baseURL = "https://Eileenbiabiabia.github.io/Eileen-card/"  # update after Pages is enabled
title = "Ailin Chu"
theme = "PaperMod"
# paginate deprecated (moved to [pagination].pagerSize)
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  [params.profileMode]
    enabled = true
    title = "Ailin Chu"
    subtitle = "M.S. in AI @ Northwestern · AI/ML · Data · Systems"
    imageUrl = "/img/profile.jpg"   # add this in step 4
    imageTitle = "Ailin"
    imageWidth = 160
    imageHeight = 240

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[outputs]
  home = ["HTML", "RSS"]

[pagination]
  pagerSize = 5
